### ISSUE TITLE
Unmarshalling error logs contain Slack user data

### ISSUE THREAD

**Issue by richgerrard** [infracloudio/botkube#579] opened 2022-05-16 20:02 UTC
**Describe the bug**
When the dependency (`nlopes/slack`) can't marshall a message event, an error is logged.
The log contains information about the event, which contains much too much information on the Slack user.

**To Reproduce**
1. Go to Slack
2. Click on the huddle icon; do it in a really public channel just to annoy lots of other people with your test.  Some of them might join to say hi!  Please tell them I said: "hello".
3. Dump the error logs of your botKube pod (`k logs botkube-blah`)
```
Slack unmarshalling error: RTM Error: Received unmapped event "user_huddle_changed": {all my info about me}
```

**Expected behavior**
Don't log things that don't matter.

**Screenshots**
n/a

**Additional context**
`nlopes/slack` has moved to `slack-go/slack`, and you should probably also update your dependency, but the problem with using this tool is that it listens to every possible slack event.
(ref: https://github.com/slack-go/slack/blob/0e14c9d4a15c91e845bc371fe91ee58763a3813a/websocket_managed_conn.go#L494)
Which means BotKube listens to every event
Which makes this tool a really frightening kind of slack spy program that's running in my kubernetes cluster and outputting employee information in error logs.

**Comment by PrasadG193** [comment] 2022-05-18 00:41
Thanks for reporting this. We will prioritize this for the upcoming release

**Comment by pkosiec** [comment] 2022-05-19 16:17
Hi @richgerrard,

Thanks for report. I've checked that, and you're absolutely right—it is caused by the `slack-go/slack` library. I've prepared a PR with fix directly to the repo: https://github.com/slack-go/slack/pull/1067

Also, to avoid being blocked, I've created a PR with a workaround on Botkube side: https://github.com/infracloudio/botkube/pull/583. I hope it will be merged soon 🤞 

Cheers!

**Closed** 2022-05-26 05:56 UTC
Labels: bug
