### ISSUE TITLE
Integration with Microsoft teams

### ISSUE THREAD

**Issue by tusharsonawanes** [infracloudio/botkube#240] opened 2020-01-10 07:46 UTC
I have used botkube with slack to send some basic commands to my kubernetes cluster. It would be very useful if the same happened through ms-teams.

**Comment by PrasadG193** [comment] 2020-01-10 07:59
Hey @tusharsonawanes ,
We are already working on this. We had to actually write go sdks first as Microsoft doesn't have official go sdks for developing MS Teams Bots. We have that work in progress here: https://github.com/infracloudio/msbotbuilder-go

**Comment by PrasadG193** [comment] 2020-01-10 07:59
Duplicate of https://github.com/infracloudio/botkube/issues/60

**Closed** 2020-01-10 08:00 UTC
Labels: duplicate, enhancement
