### ISSUE TITLE
Send Alert for Image Version Updates

### ISSUE THREAD

**Issue by mrushdan** [infracloudio/botkube#151] opened 2019-08-09 12:18 UTC
I am requesting customization to send an alert every time a container image version is updated. 
When a new deployment is applied to the cluster, pods are created using the new image and I want to alert a slack channel about this new image referencing the service name/deploy name and namespace. i.e. "$SERVICE $IMAGE has been deployed to $NAMESPACE" or something like this.

**Comment by PrasadG193** [comment] 2019-08-09 12:20
duplicate of https://github.com/infracloudio/botkube/issues/135

**Comment by PrasadG193** [comment] 2019-08-09 12:22
@mrushdan this is getting tracked under https://github.com/infracloudio/botkube/issues/131. Hence closing this issue.

**Closed by PrasadG193** 2019-08-09 12:22 UTC
Labels: enhancement
