### ISSUE TITLE
Test cases missing

### ISSUE THREAD

**Issue by arush-sal** [infracloudio/botkube#57] opened 2019-03-20 11:07 UTC
**Describe the bug**
The test cases for the code are missing which makes it harder to verify any change(s) made to the code making testing a slow and manual process.

**To Reproduce**
N/A

**Expected behavior**
There should be unit cases with at most coverage possible.

**Screenshots**
N/A

**Additional context**
N/A

**Comment by aananthraj** [comment] 2019-08-08 09:20
Looks similar to #136 
I guess this can be closed

**Comment by sanketsudake** [comment] 2019-08-21 06:30
Closing as duplicate of #136. Please follow #136 for further updates.

**Closed by sanketsudake** 2019-08-21 06:30 UTC
Labels: bug
